### ISSUE TITLE
.DS_Store is not managed by Gitignore :)

### ISSUE THREAD

**Issue by Dnomyar** [projectL3MIAGE/IHMproject#1]

**Comment by AntoineGrn** [comment]
Le '.DS_STORE' c'est quoi ?

**Comment by Dnomyar** [comment]
C'est le fichier caché créé par OSX pour se souvenir de ta configuration pour le finder, il me semble.

**Comment by AntoineGrn** [comment]
Okay d'accord et le gît ignore il fait le mettre dans le dépôt ?

**Comment by Dnomyar** [comment]
En fait il suffit de compléter celui qui est déjà la (https://github.com/projectL3MIAGE/IHMproject/blob/master/.gitignore) en ajoutant des règles. Tu peux t'aider de ce site pour générer les gitignores : https://www.gitignore.io/

**Comment by AntoineGrn** [comment]
Dac merci ^^ :)

**Comment by anaelChardan** [comment]
I just corrected it, in fact Symfony already provides a .gitignore otherwise we'll see all our password :)

**Comment by AntoineGrn** [comment]
Thanks ! :)

**Comment by Dnomyar** [comment]
I made a pull request to remove .DS_Store files

**Comment by AntoineGrn** [comment]
On l'accepte comment ?

**Comment by Dnomyar** [comment]
Tu dois avoir un bouton ici : https://github.com/projectL3MIAGE/IHMproject/pull/2

**Comment by AntoineGrn** [comment]
Oki ^^
